data:
  ip: 192.168.70.71

spring:
  datasource:
    name:  message_warning_score
    url: jdbc:mysql://${data.ip}:3313/message_warning_score?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: ${data.ip}
    password: ubuntu
    port: 6379
    timeout: 10000ms
    jedis:
      pool:
        min-idle: 0
        max-idle: 5